import { IRoleItem } from './api.interface';
export * from './api.interface';

export const roleValue = (): IRoleItem[] => {
    return [
        {
            'roleCode': 'role_super_manager',
            'roleName': '超级管理员',
            'creatorId': 0,
            'createUserName': null,
            'permissions': null,
            'creatorTime': null,
            'admin': true,
            'systemRole': true
        },
        {
            'roleCode': 'role_extendman',
            'roleName': '延保专员',
            'creatorId': 196,
            'createUserName': '测四',
            'permissions': [
                'url_extensionins',
                'url_extensionins_contract',
                'url_extensionins_contract_list',
                'button_extensioninscontract_export',
                'button_extensioninscontract_edit',
                'button_extensioninscontract_print',
                'button_extensioninscontract_del',
                'button_extensioninscontract_detail',
                'button_extensioninscontract_tuibao',
                'url_extensionins_memberpayment_list',
                'button_extensioninsmemberpayment_confirmpayment',
                'button_extensioninsmemberpayment_print',
                'url_extensionins_surrender_list',
                'button_sure_surrender'
            ],
            'creatorTime': '2019-09-09 19:46:07',
            'admin': false,
            'systemRole': true
        },
        {
            'roleCode': 'role_seatmember',
            'roleName': '坐席',
            'creatorId': 179,
            'createUserName': '太原顺宝行宝马店',
            'permissions': [
                'url_customer_manager',
                'url_customers',
                'button_customers_delete',
                'url_recyclebin',
                'button_recyclebin_emptytrash',
                'button_recyclebin_revoke',
                'url_car_insurance',
                'url_renewal',
                'replace_quote',
                'url_insuretrack',
                'url_issuelist',
                'url_defeatlist',
                'url_camera',
                'url_camera_list',
                'url_statisticalreport',
                'url_statisticalreport_workload',
                'url_statisticalreport_analysisofdefeat',
                'url_statisticalreport_outputanalysis',
                'url_marketing',
                'url_marketing_smslist',
                'button_smslist_sendsmsrecords'
            ],
            'creatorTime': '2019-06-27 00:52:50',
            'admin': false,
            'systemRole': true
        },
        {
            'roleCode': 'role_salesman',
            'roleName': '业务员',
            'creatorId': 179,
            'createUserName': '太原顺宝行宝马店',
            'permissions': [
                'url_customer_manager',
                'url_customers',
                'button_customers_assign',
                'button_customers_transfer',
                'button_customers_retrieve',
                'button_customers_insuretracksetting',
                'url_recyclebin',
                'button_recyclebin_revoke',
                'url_car_insurance',
                'url_renewal',
                'replace_quote',
                'url_insuretrack',
                'url_issuelist',
                'url_defeatlist',
                'url_extensionins',
                'url_extensionins_contract',
                'url_extensionins_contract_list',
                'button_extensioninscontract_edit',
                'button_extensioninscontract_print',
                'button_extensioninscontract_del',
                'button_extensioninscontract_detail',
                'url_extensionins_memberpayment_list',
                'button_extensioninsmemberpayment_confirmpayment',
                'button_extensioninsmemberpayment_print',
                'url_camera',
                'url_camera_list',
                'button_cameralist_assigncustomers',
                'button_cameralist_automaticassignsetting',
                'button_cameralist_carvehicle_filter',
                'url_camera_entrystore',
                'url_user_manager',
                'url_agentlist',
                'button_agentlist_add',
                'button_agentlist_edit',
                'url_rolepermission',
                'button_rolepermission_add',
                'button_rolepermission_edit',
                'url_statisticalreport',
                'url_statisticalreport_workload',
                'url_statisticalreport_customer',
                'url_statisticalreport_analysisofdefeat',
                'url_statisticalreport_outputanalysis',
                'url_marketing',
                'url_marketing_smslist',
                'button_smslist_sendsmsrecords',
                'url_system_setup',
                'url_quote_channel',
                'button_quotechannel_enabledisabled',
                'url_customer_setting',
                'url_defeat_reason_setting',
                'button_add_reason',
                'button_edit_reason',
                'button_del_reason'
            ],
            'creatorTime': '2019-06-27 00:52:50',
            'admin': false,
            'systemRole': true
        },
        {
            'roleCode': 'role_manager',
            'roleName': '续保部管理员',
            'creatorId': 179,
            'createUserName': '太原顺宝行宝马店',
            'permissions': [
                'url_customer_manager',
                'url_customers',
                'button_customers_assign',
                'button_customers_transfer',
                'button_customers_retrieve',
                'button_customers_insuretracksetting',
                'button_customers_export',
                'button_customers_delete',
                'url_dataimport',
                'button_dataimport_import',
                'url_recyclebin',
                'button_recyclebin_emptytrash',
                'button_recyclebin_revoke',
                'url_car_insurance',
                'url_renewal',
                'replace_quote',
                'url_insuretrack',
                'button_insuretrack_transfercustomers',
                'button_insuretrack_export',
                'url_issuelist',
                'button_issurelist_export',
                'url_defeatlist',
                'url_camera',
                'url_camera_list',
                'button_cameralist_assigncustomers',
                'button_cameralist_automaticassignsetting',
                'button_cameralist_carvehicle_filter',
                'button_cameralist_export',
                'url_user_manager',
                'url_agentlist',
                'button_agentlist_add',
                'button_agentlist_edit',
                'button_agentlist_delete',
                'url_rolepermission',
                'button_rolepermission_add',
                'button_rolepermission_edit',
                'button_rolepermission_delete',
                'url_statisticalreport',
                'url_statisticalreport_workload',
                'button_workload_export',
                'url_statisticalreport_analysisofdefeat',
                'url_statisticalreport_outputanalysis',
                'url_marketing',
                'url_marketing_smslist',
                'button_smslist_sendsmsrecords',
                'url_system_setup',
                'url_quote_channel',
                'button_quotechannel_enabledisabled',
                'url_customer_setting',
                'url_defeat_reason_setting',
                'button_add_reason',
                'button_edit_reason',
                'button_del_reason'
            ],
            'creatorTime': '2019-06-27 00:52:50',
            'admin': false,
            'systemRole': true
        },
        {
            'roleCode': 'role_ybbmanager',
            'roleName': '延保部管理员',
            'creatorId': 0,
            'createUserName': null,
            'permissions': [
                'url_extensionins',
                'url_extensionins_contract',
                'url_extensionins_contract_list',
                'button_extensioninscontract_export',
                'button_extensioninscontract_edit',
                'button_extensioninscontract_print',
                'button_extensioninscontract_del',
                'button_extensioninscontract_detail',
                'button_extensioninscontract_tuibao',
                'url_extensionins_memberpayment_list',
                'button_extensioninsmemberpayment_confirmpayment',
                'button_extensioninsmemberpayment_print',
                'url_extensionins_surrender_list',
                'button_sure_surrender',
                'url_user_manager',
                'url_agentlist',
                'button_agentlist_add'
            ],
            'creatorTime': '2019-09-10 09:57:26',
            'admin': false,
            'systemRole': true
        },
        {
            'roleCode': 'role_renewaler',
            'roleName': '续保员',
            'creatorId': 179,
            'createUserName': '太原顺宝行宝马店',
            'permissions': [
                'url_customer_manager',
                'url_customers',
                'button_customers_delete',
                'url_recyclebin',
                'button_recyclebin_emptytrash',
                'button_recyclebin_revoke',
                'url_car_insurance',
                'url_renewal',
                'replace_quote',
                'url_insuretrack',
                'url_issuelist',
                'url_defeatlist',
                'url_camera',
                'url_camera_list',
                'url_statisticalreport',
                'url_statisticalreport_workload',
                'url_statisticalreport_analysisofdefeat',
                'url_statisticalreport_outputanalysis',
                'url_marketing',
                'url_marketing_smslist',
                'button_smslist_sendsmsrecords'
            ],
            'creatorTime': '2019-06-27 00:52:50',
            'admin': false,
            'systemRole': true
        }
    ];
};

export const queryTotalNumberData = () => {
};
